### ISSUE TITLE
Some titles abort execution after calling EmuIDirect3D8_EnumAdapterModes

### ISSUE THREAD

**Issue by LukeUsher** [LukeUsher/Cxbx-Reloaded#22]
I am not entirely sure when this broke exactly, but some titles are either triggering a reboot to dashboard or crashing after calling EmuIDirect3D8_EnumAdapterModes. This could have been caused by attempting to port improvements from Dxbx but I am not certain.

Seems to effect mostly SEGA titles (seen with JSRF and Panzer Dragoon) but also effects a few other games.

**Comment by LukeUsher** [comment]
In Panzer Dragoon at least it seems to be attempting video modes that are not in the XboxResolutions array. I ported the code there from the Dxbx svn on source forge. I'll try instead using the code from the Dxbx version on GitHub to see how that behaves. This most likely won't be until tomorrow though

**Comment by PatrickvL** [comment]
It I remember correctly, Dxbx on github is older than the code on sourceforge

**Comment by PatrickvL** [comment]
But I have at least three more copies in various stages of development

**Comment by PatrickvL** [comment]
I'll try to sort them out and put them in GitHub branches

**Comment by StrikerX3** [comment]
It took me a while to figure out why Panzer Dragoon aborted. The game expects to find either 640x480 or 720x480 with D3DFMT_LIN_X8R8G8B8 or D3DFMT_LIN_X1R5G5B5 but the list returned by the native D3D functions for some reason didn't include any of these modes.

Since it doesn't make sense to return the list of video modes provided by the host system (we're emulating an Xbox after all), I simply made these functions enumerate the list of Xbox video modes -- the `XboxResolutions` array -- and added the screen format to the struct as well for completeness.

**Comment by LukeUsher** [comment]
Thanks, I can confirm this works for me.
