### ISSUE TITLE
EmuD3DDeferredTextureState FatalError

### ISSUE THREAD

**Issue by BiatuAutMiahn** [LukeUsher/Cxbx-Reloaded#26]
I keep getting "*EmuD3DDeferredTextureState was not found!" error on alot of xbe's I try to run.

**Comment by LukeUsher** [comment]
This usually means the game you are trying to run isn't supported by Cxbx-Reloaded.

Most of the time this is because the game makes use of Link-Time-Optimised libraries, these titles will not be supported at all until low-level NV2A emulation is implemented, this is likely to be a long time away so don't expect these particular games to run anytime soon.

**Comment by BiatuAutMiahn** [comment]
Noted, however I was attempting to run various dash xbe's can't seem to get the 3944, so i was trying everything else. The only game i'd ever intend to run is Halo 2, which un-suprisingly does not run, however it does not crash either, just throws a bunch of NV2A errors.

**Comment by LukeUsher** [comment]
Only the very early dashboard versions run as Microsoft switched to using Link-Time Optimisation in later builds.

Halo 2 is a title I haven't personally tested yet, but from what you are saying it sounds like it is another title that will be benefited by full NV2A emulation

**Comment by BiatuAutMiahn** [comment]
right, do you have any recommendations for where i can get an earlier dash that I can beta test with? My contact is on my profile.

**Comment by LukeUsher** [comment]
Personally, I use dashboard 4034 (1.00.4034.01) but I believe 4817(1.00.4817.01) also works, it might be worth trying to find one of those
